FROM node:20-alpine
WORKDIR /app

RUN npm i -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .

CMD ["pnpm", "run", "dev"]
HEALTHCHECK --interval=30s --timeout=20s --start-period=5s --retries=3 CMD curl --fail http://localhost:3005/healthcheck || exit 1
EXPOSE 3005
