FROM node:20-alpine
WORKDIR /app

COPY . .
RUN npm i -g pnpm
RUN pnpm install

CMD ["pnpm", "run", "dev"]
HEALTHCHECK --interval=30s --timeout=20s --start-period=5s --retries=3 CMD curl --fail http://localhost:3005/healthcheck || exit 1
EXPOSE 3005