FROM oven/bun:debian
WORKDIR /app

RUN apt update && apt install -y wget xz-utils && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.0-latest-linux64-gpl-7.0.tar.xz && \
  tar -xvf ffmpeg-n7.0-latest-linux64-gpl-7.0.tar.xz && \
  mv ffmpeg-n7.0-latest-linux64-gpl-7.0 /usr/local/ffmpeg && \
  ln -s /usr/local/ffmpeg/ffmpeg /usr/local/bin/ffmpeg && \
  ln -s /usr/local/ffmpeg/ffprobe /usr/local/bin/ffprobe && \
  rm ffmpeg-n7.0-latest-linux64-gpl-7.0.tar.xz

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
COPY . .

EXPOSE 3000
CMD ["bun", "dev:server"]
# HEALTHCHECK --interval=30s --timeout=20s --start-period=5s --retries=3 CMD curl --fail http://localhost:3005/healthcheck || exit 1
