name: Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      CLUSTER: bken
      DEPLOYMENT: pier
      CONTAINER_NAME: pier
      GITHUB_SHA: ${{ github.sha }}
      DO_API_KEY: ${{ secrets.DO_API_KEY }}
      REGISTRY: registry.digitalocean.com/bken/pier
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}

      - name: Build container image
        run: docker build
          --build-arg NEXT_PUBLIC_GIT_SHA=$GITHUB_SHA
          -t $REGISTRY:latest
          -t $REGISTRY:$GITHUB_SHA .

      - name: Login to DigitalOcean Docker Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $REGISTRY --all-tags

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 $CLUSTER

      - name: Update cluster image
        run: kubectl set image deployment/$DEPLOYMENT $CONTAINER_NAME=$REGISTRY:$GITHUB_SHA
