name: Deploy
env:
  BKEN_ENV: dev
  AWS_DEFAULT_REGION: us-east-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  push:
    branches:
      - dev
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # - run: cd server && yarn && yarn test
      - run: cd server && yarn
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd server && yarn install --production
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26

      - name: Terraform fmt
        id: fmt
        run: cd stack/dev && terraform fmt
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: cd stack/dev && terraform init
        continue-on-error: false

      - name: Terraform Validate
        id: validate
        run: cd stack/dev && terraform validate -no-color
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: cd stack/dev && terraform plan -no-color
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: cd stack/dev && terraform apply -auto-approve -no-color
        continue-on-error: false
