name: Deploy
env:
  JWT_KEY: ${{ secrets.JWT_KEY }}
  DO_API_KEY: ${{ secrets.DO_API_KEY }}
  DO_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
  DO_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
  DB_CONNECTION_STRING: mongodb://localhost:27017 # ${{ secrets.DB_CONNECTION_STRING }}
  WASABI_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY_ID }}
  WASABI_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_ACCESS_KEY }}
on:
  push:
    branches:
      - dev
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4
      - run: touch .env
      - run: yarn
      - run: yarn test