FROM ubuntu:24.04

WORKDIR /opt/alcoves

RUN apt update && apt install -y wget xz-utils curl unzip && rm -rf /var/lib/apt/lists/*

RUN wget -q https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz && \
  tar -xvf ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz && \
  mv ffmpeg-n7.1-latest-linux64-gpl-7.1/bin/ffmpeg /usr/local/bin/ffmpeg && \
  mv ffmpeg-n7.1-latest-linux64-gpl-7.1/bin/ffprobe /usr/local/bin/ffprobe && \
  rm -rf ffmpeg-n7.1-latest-linux64-gpl-7.1 && \
  rm ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz

RUN curl -fsSL https://bun.sh/install | BUN_INSTALL=/usr bash -s "bun-v1.2.1"

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

EXPOSE 5173
CMD ["bun", "dev"]