FROM ubuntu:24.04

WORKDIR /app

RUN apt update && apt install -y wget xz-utils curl unzip && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://bun.sh/install | BUN_INSTALL=/usr bash

RUN wget -q https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz && \
    tar -xvf ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz && \
    mv ffmpeg-n7.1-latest-linux64-gpl-7.1/bin/ffmpeg /usr/local/bin/ffmpeg && \
    mv ffmpeg-n7.1-latest-linux64-gpl-7.1/bin/ffprobe /usr/local/bin/ffprobe && \
    rm -rf ffmpeg-n7.1-latest-linux64-gpl-7.1 && \
    rm ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz

EXPOSE 3000
CMD ["bun", "dev"]