FROM oven/bun:latest
WORKDIR /app

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
COPY . .

EXPOSE 3005
CMD ["bun", "dev:server"]
HEALTHCHECK --interval=30s --timeout=20s --start-period=5s --retries=3 CMD curl --fail http://localhost:3005/healthcheck || exit 1
