openapi: 3.0.0
info:
  title: bken.io api
  description: This documentation describes the functionality of our api
  version: 0.1.0
servers:
  - url: https://api.bken.io
    description: Production Server
paths:
  /:
    get:
      summary: Returns api health check
      description: Used to determine if the api is healthy
      responses:
        '200': # status code
          description: health check message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: welcome to the api
