services:
  reef:
    restart: always
    ports:
      - 3000:3000
    build:
      context: ../reef/
      dockerfile: ../reef/docker/Dockerfile.dev
    environment:
      NEXT_PUBLIC_DEV_CSS: true
      NEXT_PUBLIC_API_ENDPOINT: "http://localhost:4000"
    volumes:
      - ../reef/.:/app
      - /app/node_modules
  atoll:
    restart: always
    ports:
      - 4000:4000
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/media
      - /app/node_modules
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass redis
    volumes:
      - redis:/data
  # prisma-studio:
  #   image: timothyjmiller/prisma-studio:latest
  #   restart: unless-stopped
  #   ports:
  #     - 5555:5555
volumes:
  redis:
  postgres:
