services:
  reef:
    restart: always
    ports:
      - 3000:3000
    build:
      context: ../reef/
      dockerfile: ../reef/docker/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ../reef/.:/app
      - /app/node_modules
  atoll:
    restart: always
    ports:
      - 4000:4000
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - .:/app
      - ./data/videos:/videos
      - ./data/config:/config
      - /app/node_modules
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    # command: redis-server --requirepass redis
    volumes:
      - redis:/data
volumes:
  redis:
  postgres:
