name: Deploy
on:
  push:
    branches:
      - development
jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy to Development
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: development
          BRANCH: deploy-development
          FOLDER: dist
          BUILD_SCRIPT: yarn && yarn build
