name: Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
      DO_API_KEY: ${{ secrets.DO_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}

      - name: Build container image
        run: docker build
          --build-arg NEXT_PUBLIC_GIT_SHA=$GITHUB_SHA
          -t registry.digitalocean.com/bken/reef:latest
          -t registry.digitalocean.com/bken/reef:$GITHUB_SHA .

      - name: Login to DigitalOcean Docker Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/bken/reef --all-tags

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 bken

      - name: Update cluster image
        run: kubectl set image deployment/reef reef=registry.digitalocean.com/bken/reef:$GITHUB_SHA
