name: Deploy
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  push:
    branches:
      - dev
jobs:
  ecr_docker_push:
    name: ECR Docker Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: kciter/aws-ecr-action@v1
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: bken/web
          region: us-east-1
          tags: dev,${{ github.sha }}
          create_repo: false
          extra_build_args: '--build-arg BKEN_ENV=dev'
  deploy:
    name: Deploy
    needs: ecr_docker_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: init
          tf_actions_working_dir: stack/dev
      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: apply
          tf_actions_working_dir: stack/dev
