name: Deploy
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      BKEN_ENV: dev
      NODE_ENV: production
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm i -g serverless
      - run: cd stack/dev && serverless
