on: push
name: Deployment
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: master
        uses: actions/bin/filter@master
        with:
          args: branch master
      - name: install
        uses: actions/npm@master
        with:
          args: install
      - name: build
        uses: actions/npm@master
        with:
          args: run build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v1.0.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
