name: Deploy

on: [push]
  branches:
    - development

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@development

      - name: Deploy to Development
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: deploy-development # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          BUILD_SCRIPT: yarn i && yarn build # The build script the action should run prior to deploying.
