name: Quality
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install, lint, build
        run: |
          yarn
          yarn lint
          yarn build
        env:
          CI: true
