# https://github.com/appleboy/ssh-action

name: Production Deployment
on:
  push:
    branches:
      - autoDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH: autoDeploy
    steps:
    - name: log into prod webserver and update from master
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: BRANCH
        script: |
          cd web
          git fetch -p && git reset --hard origin/$BRANCH && git pull
          yarn build
          pm2 reload all --update-env