# https://github.com/appleboy/ssh-action

name: Production Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: log into prod webserver and update from master
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd web
          git fetch -p && git reset --hard origin/master && git pull
          yarn build
          yarn redeploy