name: Deploy
env:
  DO_API_KEY: ${{ secrets.DO_API_KEY }}
  NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
  NOMAD_ADDRESS: ${{ secrets.NOMAD_ADDRESS }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}
      - name: Build container image
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: docker build
          --build-arg REACT_APP_GIT_SHA=$GITHUB_SHA
          -t registry.digitalocean.com/bken/reef:latest
          -t registry.digitalocean.com/bken/reef:$GITHUB_SHA .
      - name: Login to DigitalOcean Docker Registry
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/bken/reef --all-tags
      - name: Deploy job
        uses: appleboy/ssh-action@master
        env:
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.NOMAD_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          envs: NOMAD_TOKEN
          script: |
            cd /root/reef && git fetch -p && git reset --hard ${GITHUB_SHA}
            sed -i "s+:latest+:${GITHUB_SHd job.hcl
            nomad job run ./reef.json -token ${NOMAD_TOKEN}
      - name: Cleanup Repository
        run: ./scripts/doco_registry_cleanup.sh