name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
      DO_API_KEY: ${{ secrets.DO_API_KEY }}
      REGISTRY: registry.digitalocean.com/bken/reef
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}

      - name: Build container image
        run: docker build
          --build-arg NEXT_PUBLIC_GIT_SHA=$GITHUB_SHA
          -t $REGISTRY:latest
          -t $REGISTRY:$GITHUB_SHA .

      - name: Login to DigitalOcean Docker Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $REGISTRY --all-tags
