name: Test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install, build, and test
        run: |
          yarn
          yarn build
        env:
          CI: true
